### ISSUE TITLE
Proposal: Adding a CONTRIBUTING.md file to the Seldon Repository

### ISSUE THREAD

**Issue by User-DK** [seldon-code/seldon#22]
As a potential contributor to the Seldon repository, I've noticed the absence of a CONTRIBUTING.md file. This file guides contributors on coding conventions, bug reporting, feature requests, and the pull request process. I propose adding this file to streamline contributions and provide clarity to newcomers.

I would like to work on it under your guidance ....Your suggestion and thoughts are welcome.

**Comment by HaoZeke** [comment]
Hi @User-DK, thanks for the note.
