### ISSUE TITLE
Probable Initial Node Bias in DeGroot Model Implementation.

### ISSUE THREAD

**Issue by User-DK** [seldon-code/seldon#37]
The current implementation of the DeGroot model in Degroot.cpp exhibits a potential source of bias due to the deterministic selection of the initial node from which the opinion iteration begins. This deterministic selection, starting from index 0 as observed in the code, can lead to biased simulation results, as the final opinions within the network may be influenced by the order in which nodes are updated.

Here is the link:https://github.com/seldon-code/seldon/blob/229937fac6405b9a0571238ae692978f9141ddb3/src/models/DeGroot.cpp#L26

Suppose one example that we have a linear kind of network and max_iterations=2 then the node to start from(index) will decide the final opinions of the network 

A probable solution can be some randomized node selection and then building the network opinion in some graph traversal way (costly)

Don't know if this is a valid point but it took up my attention...

Thanks

**Comment by MSallermann** [comment]
Hi @User-DK!
If I understand correctly you are referring to the loop that updates the copy of the current agents: https://github.com/seldon-code/seldon/blob/229937fac6405b9a0571238ae692978f9141ddb3/src/models/DeGroot.cpp#L33-L44.
This kind of update would, indeed, be dependent on the order in which the agent opinions are updated, _if it were performed inplace_. 
Here, we update a copy of the agents, however (`agents_current_copy`).
Did I get that right? If not, could you please elaborate a little?

**Comment by User-DK** [comment]
Sorry for the oversight I forgot that the first loop just updates the current copy and not the actual network agents opinion sorry for that I understood my mistake. thanks...
