### ISSUE TITLE
Doubt: Activity Driven Model 

### ISSUE THREAD

**Issue by User-DK** [seldon-code/seldon#53]
I had a doubt that whether opinion can lie beyond the [-1,1] range because for activity driven model it does happens with this conf file
https://github.com/seldon-code/seldon/blob/main/test/res/10_agents_meanfield_activity.toml

Please if you can run the simulation and check it from the opinion output file.

if its correct then again a thought arises that this test case is passing as okay how ??
https://github.com/seldon-code/seldon/blob/3ba2520cc30e552b8b261a1103a0978a24588d0c/test/test_activity.cpp#L204-L207

**Comment by MSallermann** [comment]
Hi @User-DK, the opinions in the activity driven model can indeed lie outside the interval [-1.0,1.0]. Initializing them inside this interval is just a useful convention. So I think the the test should be fine

**Comment by HaoZeke** [comment]
Closing as answered for now :)
